; VolOSD GUI
; Generated by SmartGUI Creater
; Created by Drugwash, Oct 2008

Gui, Add, GroupBox, x6 y27 w183 h171, Monitor
Gui, Add, Radio, x14 y47 w171 h18 Checked, Always on primary monitor
Gui, Add, Radio, x14 y67 w171 h18 Disabled, Always follow active window
Gui, Add, Radio, x14 y87 w171 h18 Disabled, Use the monitor selected below:
Gui, Add, Radio, x30 y110 w151 h18 Group Checked Disabled, Monitor #1
Gui, Add, Radio, x30 y130 w151 h18 Disabled, Monitor #2
Gui, Add, Radio, x30 y150 w151 h18 Disabled, Monitor #3
Gui, Add, Radio, x30 y170 w151 h18 Disabled, Monitor #4
Gui, Add, GroupBox, x193 y27 w127 h88, Soundcard
Gui, Add, Radio, x197 y47 w121 h18 Checked, Soundcard #1
Gui, Add, Radio, x197 y67 w121 h18 Disabled, Soundcard #2
Gui, Add, Radio, x197 y87 w121 h18 Disabled, Soundcard #3
Gui, Add, Text, x198 y125 w124 h76 Disabled, Note:`nDue to OS limitations Windows 95 && NT will always display OSD on primary monitor.
Gui, Add, GroupBox, x324 y27 w143 h149, Detected devices
Gui, Add, Text, x338 y40 w90 h15, Monitors:
Gui, Add, Text, x327 y55 w10 h12, 1.
Gui, Add, Text, x338 y55 w127 h12, Monitor #1
Gui, Add, Text, x327 y68 w10 h12, 2.
Gui, Add, Text, x338 y68 w127 h12, Monitor #2
Gui, Add, Text, x327 y81 w10 h12, 3.
Gui, Add, Text, x338 y81 w127 h12, Monitor #3
Gui, Add, Text, x327 y94 w10 h12, 4.
Gui, Add, Text, x338 y94 w127 h12, Monitor #4
Gui, Add, Text, x338 y115 w90 h15, Soundcards:
Gui, Add, Text, x327 y130 w10 h12, 1.
Gui, Add, Text, x338 y130 w127 h12, Soundcard #1
Gui, Add, Text, x327 y143 w10 h12, 2.
Gui, Add, Text, x338 y143 w127 h12, Soundcard #2
Gui, Add, Text, x327 y156 w10 h12, 3.
Gui, Add, Text, x338 y156 w127 h12, Soundcard #3
Gui, Add, Checkbox, x328 y184 w137 h18 Checked, Start with Windows
Gui, Add, GroupBox, x6 y203 w183 h165, Appearance
Gui, Add, Text, x14 y220 w100 h16, Progress bar width:
Gui, Add, Button, x119 y217 w62 h22, Default
Gui, Add, Slider, x14 y240 w164 h25 vsetW Range50-500 TickInterval50 ToolTip, 120
Gui, Add, Text, x14 y270 w100 h16, Progress bar height:
Gui, Add, Button, x119 y266 w62 h22, Default
Gui, Add, Slider, x14 y290 w164 h25 vsetH Range5-20 TickInterval1 ToolTip, 8
Gui, Add, Text, x14 y320 w60 h14, Master:
Gui, Add, ListView, x76 y320 w40 h13 -E0x200 +Border -hdr +ReadOnly BackgroundFF0000 vcp1
Gui, Add, Text, x14 y334 w60 h14, Wave:
Gui, Add, ListView, x76 y334 w40 h13 -E0x200 +Border -hdr +ReadOnly Background0000FF vcp2
Gui, Add, Text, x14 y348 w60 h14, Background:
Gui, Add, ListView, x76 y348 w40 h13 -E0x200 +Border -hdr +ReadOnly BackgroundSilver vcp3
Gui, Add, Button, x119 y316 w62 h22, Default
Gui, Add, Checkbox, x119 y345 w68 h19, XP theme
Gui, Add, Checkbox, x385 y340 w77 h19, No tray icon
Gui, Add, GroupBox, x193 y203 w275 h165, Hotkeys
Gui, Add, Text, x198 y221 w67 h14, Master up:
Gui, Add, Edit, x268 y220 w110 h19, CTRL+Up
Gui, Add, Text, x198 y241 w67 h14, Master down:
Gui, Add, Edit, x268 y240 w110 h19, CTRL+Down
Gui, Add, Text, x198 y261 w67 h14, Wave up:
Gui, Add, Edit, x268 y260 w110 h19, RALT+Up
Gui, Add, Text, x198 y281 w67 h14, Wave down:
Gui, Add, Edit, x268 y280 w110 h19, RALT+Down
Gui, Add, Text, x198 y301 w67 h14, Master dim:
Gui, Add, Edit, x268 y300 w110 h19, CTRL+SHIFT+Up
Gui, Add, Text, x198 y321 w66 h14, Mute:
Gui, Add, Edit, x268 y320 w110 h19, CTRL+SHIFT+Down
Gui, Add, Text, x198 y341 w67 h14 Disabled, Options:
Gui, Add, Edit, x268 y340 w110 h19 Disabled, CTRL+SHIFT+O
Gui, Add, Button, x395 y220 w62 h32 Disabled, &Apply
Gui, Add, Button, x395 y260 w62 h32 Default, &Close
Gui, Add, Button, x395 y300 w62 h32 Disabled, Ca&ncel
Gui, Show, x228 y9 h375 w475, VolOSD options
Return

ButtonClose:
GuiClose:
ExitApp
