; VolOSD GUI
; Generated by SmartGUI Creater
; Created by Drugwash, Oct 2008

Gui, Add, Tab2, x5 y5 w326 h300 -Wrap +Theme -Background -0x800 0x3040 AltSubmit, Appearance|Hotkeys|Monitor|Soundcard|General|About
Gui, Tab
Gui, Add, Button, x130 y310 w62 h22 Disabled, &Apply
Gui, Add, Button, x194 y310 w62 h22 Default, &Close
Gui, Add, Button, x258 y310 w62 h22 Disabled, Ca&ncel
Gui, Show, x228 y9 h338 w335, VolOSD options
;============== TAB 1 ================
Gui, Tab, 1
Gui, Add, GroupBox, x11 y+5 w310 h135, Size
Gui, Add, Text, x20 y50 w100 h16, Progress bar width:
Gui, Add, Button, x245 yp w62 h22, Default
Gui, Add, Slider, x20 y75 w290 h25 vsetW Range50-500 TickInterval10 ToolTip, 120
Gui, Add, Text, x20 y105 w100 h16, Progress bar height:
Gui, Add, Button, x245 yp w62 h22, Default
Gui, Add, Slider, x20 y130 w290 h25 vsetH Range5-20 TickInterval1 ToolTip, 8
Gui, Add, GroupBox, x11 y170 w310 h122, Colors
Gui, Add, Checkbox, x20 y193 w100 h19, Use XP theme
Gui, Add, Button, x245 y190 w62 h22, Default
Gui, Add, Text, x180 y218 w60 h14 Right, Master:
Gui, Add, ListView, x+5 yp-3 w60 h20 -E0x200 +Border -hdr +ReadOnly BackgroundFF0000 vcp1
Gui, Add, Text, x180 y243 w60 h14 Right, Wave:
Gui, Add, ListView, x+5 yp-3 w60 h20 -E0x200 +Border -hdr +ReadOnly Background0000FF vcp2
Gui, Add, Text, x180 y268 w60 h14 Right, Background:
Gui, Add, ListView, x+5 yp-3 w60 h20 -E0x200 +Border -hdr +ReadOnly BackgroundSilver vcp3
;============== TAB 2 ================
Gui, Tab, 2
Gui, Add, GroupBox, x11 y+5 w310 h260, Hotkeys
Gui, Add, Text, x20 y50 w90 h14 Right, Master up:
Gui, Add, Edit, x+5 y47 w170 h20, CTRL+Up
Gui, Add, Text, x20 y75 w90 h14 Right, Master down:
Gui, Add, Edit, x+5 y72 w170 h20, CTRL+Down
Gui, Add, Text, x20 y100 w90 h14 Right, Wave up:
Gui, Add, Edit, x+5 y97 w170 h20, RALT+Up
Gui, Add, Text, x20 y125 w90 h14 Right, Wave down:
Gui, Add, Edit, x+5 y122 w170 h20, RALT+Down
Gui, Add, Text, x20 y150 w90 h14 Right, Master dim:
Gui, Add, Edit, x+5 y147 w170 h20, CTRL+SHIFT+Up
Gui, Add, Text, x20 y175 w90 h14 Right, Mute:
Gui, Add, Edit, x+5 y172 w170 h20, CTRL+SHIFT+Down
Gui, Add, Text, x20 y200 w90 h14 Right Disabled, Options:
Gui, Add, Edit, x+5 y197 w170 h20 Disabled, CTRL+SHIFT+O
Gui, Add, Text, x20 y225 w90 h14 Right Disabled, Cycle soundcards:
Gui, Add, Edit, x+5 y222 w170 h20 Disabled, CTRL+SHIFT+Enter
Gui, Add, Text, x20 y245 w290 h45 Center Disabled, Note: The 'Options' hotkey is only available when there is no tray icon. To disable the tray icon, mark 'No tray icon' in the 'General' panel.
;============== TAB 3 ================
Gui, Tab, 3
Gui, Add, GroupBox, x11 y+5 w310 h260, Behavior
Gui, Add, Radio, x20 y50 w290 h18 Checked, Always on primary monitor
Gui, Add, Radio, x20 y+2 wp hp Disabled, Always follow active window
Gui, Add, Radio, x20 y+2 wp hp Disabled, Use the monitor selected below:
Gui, Add, Radio, xp+15 y+5 w280 hp Group Checked Disabled, Monitor #1
Gui, Add, Radio, xp y+2 wp hp Disabled, Monitor #2
Gui, Add, Radio, xp y+2 wp hp Disabled, Monitor #3
Gui, Add, Radio, xp y+2 wp hp Disabled, Monitor #4
Gui, Add, Text, x20 y257 w290 h30 Center Disabled, Note: Due to OS limitations`, Windows 95 && NT will always display OSD on primary monitor.
;============== TAB 4 ================
Gui, Tab, 4
Gui, Add, GroupBox, x11 y+5 w310 h260, Device control
Gui, Add, Radio, x20 y50 w290 h18 Checked, Always use the following card:
Gui, Add, Radio, x20 y140 wp hp, Cycle through the following (using hotkey):
Gui, Add, Radio, xp+15 y75 w280 hp Group Checked, Soundcard #1
Gui, Add, Radio, xp y+2 wp hp Disabled, Soundcard #2
Gui, Add, Radio, xp y+2 wp hp Disabled, Soundcard #3
Gui, Add, Checkbox, xp y160 w280 hp Checked vscard1, Soundcard #1
Gui, Add, Checkbox, xp y+2 wp hp Checked vscard2, Soundcard #2
Gui, Add, Checkbox, xp y+2 wp hp Checked vscard3, Soundcard #3
;============== TAB 5 ================
Gui, Tab, 5
Gui, Add, GroupBox, x11 y+5 w310 h100, Detected monitors
Gui, Add, Text, x20 y50 w10 h14, 1.
Gui, Add, Text, x+1 yp w280 h14, Monitor #1
Gui, Add, Text, x20 y+6 w10 h14, 2.
Gui, Add, Text, x+1 yp w280 h14, Monitor #2
Gui, Add, Text, x20 y+6 w10 h14, 3.
Gui, Add, Text, x+1 yp w280 h14, Monitor #3
Gui, Add, Text, x20 y+6 w10 h14, 4.
Gui, Add, Text, x+1 yp w280 h14, Monitor #4
Gui, Add, GroupBox, x11 y135 w310 h80, Detected soundcards
Gui, Add, Text, x20 yp+18 w10 h14, 1.
Gui, Add, Text, x+1 yp w280 h14, Soundcard #1
Gui, Add, Text, x20 y+6 w10 h14, 2.
Gui, Add, Text, x+1 yp w280 h14, Soundcard #2
Gui, Add, Text, x20 y+6 w10 h14, 3.
Gui, Add, Text, x+1 yp w280 h14, Soundcard #3
Gui, Add, Checkbox, x20 y255 w100 h18, No tray icon
Gui, Add, Checkbox, x20 y275 w200 h18 Checked, Start with Windows
Return

ButtonClose:
GuiClose:
ExitApp
