; Generated by SmartGUI Creater

Gui, Add, ListBox, x6 y7 w161 h264,
Gui, Add, Text, x177 y8 w99 h15, Menu item name:
Gui, Add, Edit, x176 y24 w191 h24, Name
Gui, Add, Text, x176 y57 w100 h18, File path:
Gui, Add, Edit, x177 y76 w340 h22, Location
Gui, Add, Button, x518 y76 w70 h22, Browse
Gui, Add, Button, x176 y108 w100 h30, Insert
Gui, Add, Button, x176 y147 w100 h30, Remove
Gui, Add, Button, x176 y188 w100 h30, Insert separator
Gui, Show, x336 y296 h305 w596, Generated using SmartGUI 2.5
Return

GuiClose:
ExitApp