; SPLASH.SYS parameter patcher tool, for use with WBL.COM by PassingBy
; version 2.0.1.0
; Drugwash, March 2008
; Generated by SmartGUI Creater

#SingleInstance, force
Gui, Submit, NoHide
Gui, Add, Text, x6 y1 w135 h20, Input your values below:
Gui, Add, Text, x6 y20 w67 h20 right, Position H :
Gui, Add, Text, x6 y50 w67 h20 right, Position V :
Gui, Add, Text, x6 y80 w67 h20 right, Width :
Gui, Add, Text, x6 y110 w67 h20 right, Height :
Gui, Add, Text, x6 y140 w67 h20 right, Range :
Gui, Add, Edit, x76 y17 w40 h20 Number Limit3, 1
Gui, Add, UpDown, vPosH Range1-638, 1
GuiControl,, posH, %cposH%
PosH_TT := "Horizontal position of the progressbar top-left corner"
Gui, Add, Edit, x76 y47 w40 h20 Number Limit3, 1
Gui, Add, UpDown, vPosV Range1-478, 1
GuiControl,, posV, %cposV%
PosV_TT := "Vertical position of the progressbar top-left corner"
Gui, Add, Edit, x76 y77 w40 h20 Number Limit3, 1
Gui, Add, UpDown, vProgW Range1-450, 1
GuiControl,, progW, %cprogW%
ProgW_TT := "Progressbar (bullet) width"
Gui, Add, Edit, x76 y107 w40 h20 Number Limit3, 1
Gui, Add, UpDown, vProgH Range1-100, 1
GuiControl,, progH, %cprogH%
ProgH_TT := "Progressbar (bullet) height"
Gui, Add, Edit, x76 y137 w40 h20 Number Limit3,1
Gui, Add, UpDown, vProgL Range1-638, 1
GuiControl,, progL, %cprogL%
ProgL_TT := "Animation shaft width"
Gui, Submit, NoHide
Gui, Add, Text, x118 y20 w17 h15, px
Gui, Add, Text, x118 y50 w17 h15, px.
Gui, Add, Text, x118 y80 w17 h15, px.
Gui, Add, Text, x118 y110 w17 h15, px.
Gui, Add, Text, x118 y140 w17 h15, px.
Gui, Add, Button, x6 y161 w40 h25 default, Open
Open_TT := "Open a bitmap file to be patched"
Gui, Add, Button, x51 y161 w40 h25, Patch
Patch_TT := "Add the values to your bitmap"
Gui, Add, Button, x96 y161 w40 h25, Exit
Exit_TT := "Close the program"
Gui, Show, h192 w142, LogoTool 2
OnMessage(0x200, "WM_MOUSEMOVE")
Return

WM_MOUSEMOVE()
{
    static CurrControl, PrevControl, _TT  ; _TT is kept blank for use by the ToolTip command below.
    CurrControl := A_GuiControl
    if (CurrControl <> PrevControl and not InStr(CurrControl, " "))
    {
        ToolTip  ; Turn off any previous tooltip.
        SetTimer, DisplayToolTip, 1000
        PrevControl := CurrControl
    }
    return

    DisplayToolTip:
    SetTimer, DisplayToolTip, Off
    ToolTip % %CurrControl%_TT  ; The leading percent sign tell it to use an expression.
    SetTimer, RemoveToolTip, 3000
    return

    RemoveToolTip:
    SetTimer, RemoveToolTip, Off
    ToolTip
    return
}

ButtonOpen:
Gui +OwnDialogs
FileSelectFile, mylogo, 3, .\, Open a bitmap file, Logo bitmaps (*.bmp; splash.sys)
	if mylogo =
	{
		MsgBox, 12336, Error, You haven't selected a bitmap file to patch.,
		return
	}
	else
;		MsgBox, You selected the file :`n%mylogo%
FileGetSize, Lsize, %mylogo%
	if Lsize <> 308278
	{
		MsgBox, 12336, Error, The file is %Lsize% bytes.`n`nYou chose an inappropriate file to patch.`nPlease choose a 640x480px 256colors bitmap.,
		return
	}
	else
	{
mystring := VarSetCapacity(topatch, 308278, 0)
		FileRead, topatch, %mylogo%
		cposH := *(&topatch + 57) + *(&topatch + 61)*256
		cposV := *(&topatch + 65) + *(&topatch + 69)*256
		cprogW := *(&topatch + 73) + *(&topatch + 77)*256
		cprogH := *(&topatch + 81) + *(&topatch + 85)*256
		cprogL := *(&topatch + 89) + *(&topatch + 93)*256
;		MsgBox, The file is %Lsize% bytes.`nVariables are as following:`ncurrent PosH=%cposH% - new=%PosH%`ncurrent PosV=%cposV% - new=%PosV%`ncurrent ProgW=%cprogW% - new=%ProgW%`ncurrent ProgH=%cprogH% - new=%ProgH%`ncurrent ProgL=%cprogL% - new=%ProgL%
Gui, Submit, NoHide
GuiControl,, t1, %cposH%
GuiControl,, t2, %cposV%
GuiControl,, t3, %cprogW%
GuiControl,, t4, %cprogH%
GuiControl,, t5, %cprogL%
GuiControl,, posH, %cposH%
GuiControl,, posV, %cposV%
GuiControl,, progW, %cprogW%
GuiControl,, progH, %cprogH%
GuiControl,, progL, %cprogL%
	}
return

ButtonPatch:
Gui, Submit, NoHide
	tv1 := Floor(PosH/256)
	tv0 := PosH - tv1*256
	tv3 := Floor(PosV/256)
	tv2 := PosV - tv3*256
	tv5 := Floor(ProgW/256)
	tv4 := ProgW - tv5*256
	tv7 := Floor(ProgH/256)
	tv6 := ProgH - tv7*256
	tv9 := Floor(ProgL/256)
	tv8 := ProgL - tv9*256
SetFormat, INTEGER, D
		NumPut(tv0, topatch, 57, "UChar")
		NumPut(tv1, topatch, 61, "UChar")
		NumPut(tv2, topatch, 65, "UChar")
		NumPut(tv3, topatch, 69, "UChar")
		NumPut(tv4, topatch, 73, "UChar")
		NumPut(tv5, topatch, 77, "UChar")
		NumPut(tv6, topatch, 81, "UChar")
		NumPut(tv7, topatch, 85, "UChar")
		NumPut(tv8, topatch, 89, "UChar")
		NumPut(tv9, topatch, 93, "UChar")
		NumPut(84, topatch, 6, "UChar")
		NumPut(68, topatch, 7, "UChar")
		NumPut(80, topatch, 8, "UChar")
		NumPut(50, topatch, 9, "UChar")
		FileSelectFile, patched, s26, .\SPLASH.SYS, Save patched bitmap as:, WBL logo files (splash.sys)
	if patched =
	{
		MsgBox, 12336, Error, You haven't selected a name for saving the patched file.,
		return
	}
	hFile := DllCall("CreateFile", str, patched, Uint, 0x40000000, Uint, 0, Uint, 0, Uint, 2, Uint, 0, Uint, 0)
	if not hFile
	{
	    MsgBox Couldn't create "%patched%".
	    return
	}
	DllCall("WriteFile", UInt, hFile, str, topatch, UInt, mystring, UIntP, BytesActuallyWritten, UInt, 0)
	DllCall("CloseHandle", UInt, hFile)
;	MsgBox I have written %BytesActuallyWritten% bytes.`n`n`nVariable 'topatch' is %mystring% bytes.
	hFile := DllCall("CreateFile", str, patched, UInt, 0x80000000, UInt, 1|2, UInt, 0, UInt, 3, Uint, 0, UInt, 0)
	if not hFile
	{
	    MsgBox Can't open "%patched%" for reading.
	    return
	}
	BytesToRead := VarSetCapacity(topatch, StrLen(topatch))
	DllCall("ReadFile", UInt, hFile, str, topatch, UInt, BytesToRead, UIntP, BytesActuallyRead, UInt, 0)
	DllCall("CloseHandle", UInt, hFile)  ; Close the file.
		nposH := *(&topatch + 57) + *(&topatch + 61)*256
		nposV := *(&topatch + 65) + *(&topatch + 69)*256
		nprogW := *(&topatch + 73) + *(&topatch + 77)*256
		nprogH := *(&topatch + 81) + *(&topatch + 85)*256
		nprogL := *(&topatch + 89) + *(&topatch + 93)*256
		wtrmrk := Chr(*(&topatch + 6)) . Chr(*(&topatch + 7)) . Chr(*(&topatch + 8)) . Chr(*(&topatch + 9))
;		MsgBox The following values were written to the file :`ncurrent PosH=%nposH%`ncurrent PosV=%nposV%`ncurrent ProgW=%nprogW%`ncurrent ProgH=%nprogH%`ncurrent ProgL=%nprogL%`nwatermark=%wtrmrk%
return

ButtonExit:
GuiClose:
ExitApp