; Generated by SmartGUI Creater

Gui, Add, Button, x2 y3 w16 h48, <
Gui, Add, Button, x376 y4 w15 h48, >
Gui, Add, Pic, x33 y15 w540 h-22, C:\Utils\06\Customize\AvatarsLocal\icon4.ico
Gui, Add, Pic, x22 y4 w47 h47, C:\Utils\06\Customize\AvatarsLocal\dummy.jpg
Gui, Add, Edit, x3 y53 w388 h46,
Gui, Show, x314 y350 h103 w392, Generated using SmartGUI 2.5
Return

GuiClose:
ExitApp