; Generated by SmartGUI Creater

Gui, Add, Text, x185 y75 w270 h30, Welcome to the Miranda IM Custom Installer!
Gui, Add, Text, x185 y120 w270 h79, This guide will help you set up Miranda IM according to your preferences, with a few more in-depth details than the official installer. Please choose your options carefully.
Gui, Add, Button, x196 y328 w70 h30, &Back
Gui, Add, Button, x286 y328 w70 h30, &Next
Gui, Add, Button, x376 y328 w70 h30, &Exit
Gui, Add, Text, x185 y7 w270 h50, Miranda IM Custom Installer
Gui, Add, Pic, x6 y7 w171 h310, E:\Downloads\Other\Pictures\Dianne Patrice Bloom\l_2fdc0bd2bdd64741129c923f9c037252.jpg
Gui, Add, Text, x37 y340 w109 h20, © 2008 Drugwash
Gui, Show, x242 y192 h373 w472, MCI - Miranda IM Custom Installer
Return

GuiClose:
ExitApp