; Generated by SmartGUI Creater

Gui, Add, Button, x196 y328 w70 h30, &Back
Gui, Add, Button, x286 y328 w70 h30, &Next
Gui, Add, Button, x376 y328 w70 h30, &Exit
Gui, Add, Pic, x6 y7 w171 h310, E:\Downloads\Other\Pictures\Dianne Patrice Bloom\l_2fdc0bd2bdd64741129c923f9c037252.jpg
Gui, Add, Text, x37 y340 w109 h20, © 2008 Drugwash
Gui, Add, Text, x187 y38 w269 h15, Is this setup fixed or mobile (USB, CD,etc)?
Gui, Add, DropDownList, x188 y54 w130 h14, Fixed||Mobile
Gui, Add, Text, x187 y78 w269 h15, How many people will use this Miranda setup?
Gui, Add, DropDownList, x187 y94 w130 h17, Only me||Family/Office
Gui, Add, Text, x193 y83 w270 h15, Are you planning to run this on a Win9x machine?
Gui, Add, DropDownList, x198 y98 w129 h21, No||Yes/Not sure
Gui, Add, Text, x186 y120 w271 h69, According to your answers above you should install the Unicode version of Miranda IM. The zip I've just unpacked contains an ANSI build, only required on a Win95/98/ME system. Is there a strong reason to keep this version or should we go search for the Unicode one?
Gui, Add, DropDownList, x187 y190 w130 h19, Go for Unicode||Keep the ANSI
Gui, Add, Text, x186 y211 w271 h41, OK, now make sure you download the Unicode build. Clicking 'Next' will take you back to the zip selection page. Do that when the download is complete.
Gui, Add, Text, x187 y216 w272 h54, As you wish... But please remember that you would need the Unicode build if you want to see status messages that use Asian, Hebrew, Cyrillic fonts and/or you want to chat using any of those languages on an English system.
Gui, Add, Text, x186 y222 w271 h92, If my information is correct, you are currently using an ANSI operating system (%A_OSVersion%). However, you are trying to install the Unicode build of Miranda IM. Unless you have enhanced your system with some unofficial patches/updates, this will NOT work. It is recommended that you download and install the ANSI build instead.`nWhat is your choice?
Gui, Add, DropDownList, x186 y301 w171 h17, Return to zip selection page|Download ANSI build|Keep the Unicode
Gui, Show, x242 y192 h373 w472, Generated using SmartGUI 2.5
Return

GuiClose:
ExitApp