; http://www.autohotkey.com/forum/viewtopic.php?p=315671#315671
/*
Abs2Rel v3
  by aikscroll
    www.mevets.com
*/

test =
(
Gui, Add, Button, x6 y10 w80 h30 , Button
Gui, Add, CheckBox, x6 y50 w110 h30 , CheckBox
Gui, Add, Radio, x56 y100 w100 h30 , Radio
Gui, Add, Text, x6 y100 w40 h30 , Text
Gui, Add, GroupBox, x126 y10 w90 h70 , GroupBox
Gui, Add, Picture, x136 y30 w20 h20 , C:\Documents and Settings\Owner\Desktop\UI\tab.gif
Gui, Add, DropDownList, x226 y20 w100 h20 , DropDownList
Gui, 2:Add, ComboBox, x226 y50 w100 h20 , ComboBox
Gui, 2:Add, ListBox, x166 y90 w100 h30 , ListBox
Gui, 3:Add, ListView, x336 y10 w130 h60 , ListView
Gui, 3:Add, DateTime, x6 y140 w100 h30 ,
Gui, 3:Add, MonthCal, x276 y80 w190 h160 ,
Gui, 3:Add, Progress, x116 y140 w90 h20 , 25
Gui, 3:Add, Slider, x6 y180 w100 h30 , 25
Gui, 3:Add, Hotkey, x116 y170 w100 h20 ,
Gui, 3:Add, Tab, x6 y250 w460 h120 , Tab1|Tab2
; Generated using SmartGUI Creator 4.0
Gui, Show, x130 y91 h377 w477, New GUI Window
Gui, 2:Show, x125 y81 h377 w477, New GUI Window
Gui, 3:Show, x100 y81 h377 w477, New GUI Window
Return

GuiClose:
ExitApp
Return
)

Gui, Add, Text, , Paste your Gui code, as generated by Rajat's SGUI, below and then press 'Fix'.
Gui, Add, Edit, w400 h200 xp+0 yp+25 vtxtSource gSource, %Clipboard%
Gui, Add, Button, xp+0 yp+210 vbtnShow gShow, Show me a typical script
Gui, Add, Button, w100 xp+300 yp+0 vbtnFix gFix, Fix
Gui, Show, , Abs2Rel v3

Return

Fix:
  Gui, Submit, NoHide
 
  txtSource := abs2rel(txtSource) 

  GuiControl, , txtSource, %txtSource%
  clipboard = %txtsource%
 
Return

Show:
  GuiControl, , txtSource, %test%
Return

Source:
Return

GuiClose:
  ExitApp
Return


abs2rel(txtsource) {
  Loop, parse, allCounts, `,
  {
    storeXs%A_Index% =
    storeYs%A_Index% =
  }
  allCounts =
  coordX =
  coordY =
 
  Loop, Parse, txtSource, `n
  {
    StringReplace, noGui, A_LoopField, Gui`,%A_Space%
    StringMid, GuiCountNum, noGui, 1, 1
    StringMid, GuiCountColon, noGui, 2, 1
    If GuiCountNum is Number
    {
      If (GuiCountColon = ":")
      {
        StringTrimLeft, noGui, noGui, 2
        GuiCount = %GuiCountNum%
      }
    }
    Else
      GuiCount = 1
    StringMid, strShow, noGui, 1, 4
    StringReplace, noGuiAdd, noGui, Add`,
    findComma := InStr(noGuiAdd, "`,")
    findComma++
    StringMid, noCtype, noGuiAdd, %findComma%

    ;get x
    coordX =
    findX := InStr(noCtype, "x")
    Loop
    {
      findX++
      StringMid, num, noCtype, %findX%, 1
      If num is Number
        coordX = %coordX%%num%
      Else
      {
        If coordX is Number ;notice: coordX not num
        {
          If (strShow <> "Show")
          {
            storeXs%GuiCount% := storeXs%GuiCount% . "`n" . coordX
            If GuiCount not in %allCounts%
              allCounts = %allCounts%,%GuiCount%
          }
        }
        Break
      }
    }

    ;get y
    coordY =
    findY := InStr(noCtype, "y")
    Loop
    {
      findY++
      StringMid, num, noCtype, %findY%, 1
      If num is Number
        coordY = %coordY%%num%
      Else
      {
        If coordY is Number
        {
          If strShow <> "Show")
            storeYs%GuiCount% := storeYs%GuiCount% . "`n" . coordY
        }
        Break
      }
    }
  }

  StringTrimLeft, allCounts, allCounts, 1
  Loop, Parse, allCounts, `,
  {
    StringTrimLeft, storeXs%A_Loopfield%, storeXs%A_Loopfield%, 1
    StringTrimLeft, storeYs%A_Loopfield%, storeYs%A_Loopfield%, 1
    StringSplit, arrXs%A_Loopfield%, storeXs%A_Loopfield%, `n
    StringSplit, arrYs%A_Loopfield%, storeYs%A_Loopfield%, `n
    Loop, % arrXs%A_Loopfield%0
    {
      next := A_Index + 1
      diffX := arrXs%A_Loopfield%%next% - arrXs%A_Loopfield%%A_Index%
      diffY := arrYs%A_Loopfield%%next% - arrYs%A_Loopfield%%A_Index%
      If diffX >= 0
        diffX = +%diffX%
      If diffY >= 0
        diffY = +%diffY%
      txtX := arrXs%A_Loopfield%%next%
      txtY := arrYs%A_Loopfield%%next%
      txtSearch := "x" . txtX . A_Space . "y" . txtY
      txtRep := "xp" . diffX . A_Space . "yp" . diffY
      StringReplace, txtSource, txtSource, %txtSearch%, %txtRep%
    }
  }
   Return txtSource
}

